version: '2'
services:
  db:
    image: mariadb:10.5
    restart: 'no'
    environment:
      MYSQL_DATABASE: lvstrm
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_USER: rt
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql/
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminlvstrm
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 900M
    restart: always
    ports:
      - 888:80
volumes:
  mysql-data:
