version: '3.9'
services:
  db:
    image: mariadb:11.2
    restart: 'no'
    environment:
      MYSQL_DATABASE: lvstrm
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_USER: rt
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql/
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminlvstrm
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    restart: always
    ports:
      - 888:80
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - 'start'
      - '--all'
      - '--config'
      - '/etc/ngrok.yml'
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
volumes:
  mysql-data:
